name: Test & Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - run: docker build -t jaxxeh/docker-svelte -f Dockerfile.dev .
      # - run: docker run -e CI=true jaxxeh/docker-svelte npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-svelte
          environment_name: Docker-svelte-env
          existing_bucket_name: elasticbeanstalk-eu-west-3-755204287900
          region: eu-west-3
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip